// Generated by CoffeeScript 1.3.3
(function() {
  var background;

  if (!(window.mem0r1es != null)) {
    window.mem0r1es = {};
  }

  window.mem0r1es.Background = (function() {

    function Background() {}

    Background.prototype.init = function() {
      this.storageManager = new mem0r1es.StorageManager();
      this.storageManager.openDB();
      this.icon = new mem0r1es.Icon();
      this.navigationListener = new mem0r1es.NavigationListener();
      return this.setupMessageListener();
    };

    Background.prototype.sendMessage = function(tabId, message, callback) {
      chrome.tabs.sendMessage(tabId, message, function(response) {
        callback(response);
      });
    };

    Background.prototype.setupMessageListener = function() {
      var _this = this;
      chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
        console.log("redirecting a message to " + request.module);
        switch (request.module) {
          case "storageManager":
            _this.storageManager.onMessage(request.message, sendResponse);
            break;
          case "navigationListener":
            _this.navigationListener.onMessage(request.message, sendResponse);
            break;
          default:
            console.log("Could not redirect the message from the popup user interface. " + request.module + " is not a valid module");
        }
        return true;
      });
    };

    return Background;

  })();

  background = new mem0r1es.Background;

  background.init();

}).call(this);
