// Generated by CoffeeScript 1.3.3
(function() {

  if (!(window.mem0r1es != null)) {
    window.mem0r1es = {};
  }

  mem0r1es.injectable = {};

  mem0r1es.injectable.DOMtoJSON = function(node) {
    var DOMAttributes, DOMChildren, JSONNode, i, _i, _j, _ref, _ref1;
    JSONNode = {};
    JSONNode.tag = node.nodeName.toLowerCase();
    JSONNode.attributes = {};
    DOMAttributes = node.attributes;
    for (i = _i = 0, _ref = DOMAttributes.length - 1; _i <= _ref; i = _i += 1) {
      JSONNode.attributes[DOMAttributes[i].name] = DOMAttributes[i].value;
    }
    if (JSONNode.attributes.length === 0) {
      delete JSONNode.attributes;
    }
    JSONNode.children = new Array();
    DOMChildren = node.childNodes;
    for (i = _j = 0, _ref1 = DOMChildren.length - 1; _j <= _ref1; i = _j += 1) {
      if (node.childNodes[i].nodeType === 1) {
        JSONNode.children.push(mem0r1es.injectable.DOMtoJSON(DOMChildren[i]));
      }
      if (DOMChildren[i].nodeType === 3 && JSONNode.tag !== "script" && DOMChildren[i].nodeValue.replace(/[\n\t]*/g, "").length !== 0) {
        JSONNode.text = DOMChildren[i].nodeValue.replace(/[\n\t]*/g, "");
      }
    }
    return JSONNode;
  };

  mem0r1es.injectable.sendMessage = function(module, message, callback) {
    chrome.extension.sendMessage({
      module: module,
      message: message
    }, function(response) {
      if (callback != null) {
        callback(response);
      }
    });
  };

  mem0r1es.injectable.clickListener = function(event) {
    console.log(this);
  };

  mem0r1es.injectable.sendMessage("navigationListener", {
    title: "DOMtoJSON",
    content: mem0r1es.injectable.DOMtoJSON(document.getElementsByTagName("html")[0])
  });

}).call(this);
