// Generated by CoffeeScript 1.3.3
(function() {

  if (!(window.mem0r1es != null)) {
    window.mem0r1es = {};
  }

  window.mem0r1es.NavigationListener = (function() {

    function NavigationListener() {
      chrome.webNavigation.onCompleted.addListener(this.onCompleted, {
        urls: ["*://*/*"]
      }, []);
    }

    NavigationListener.prototype.getDOMCallback = function(response) {
      return console.log(response);
    };

    NavigationListener.prototype.onMessage = function(response) {
      switch (response.title) {
        case "DOMtoJSON":
          return this.getDOMCallback(response.content);
      }
    };

    NavigationListener.prototype.onCompleted = function(details) {
      console.log("(" + details.tabId + ") " + details.url);
      if (!details.url.match("about:blank")) {
        return chrome.tabs.executeScript(details.tabId, {
          file: "js/injectable.js"
        });
      }
    };

    return NavigationListener;

  })();

}).call(this);
