// Generated by CoffeeScript 1.3.3
(function() {
  var popup,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if (!(window.mem0r1es != null)) {
    window.mem0r1es = {};
  }

  window.mem0r1es.Popup = (function() {

    function Popup() {
      this.clearDBCallback = __bind(this.clearDBCallback, this);

      this.createListeners = __bind(this.createListeners, this);
      document.addEventListener('DOMContentLoaded', this.createListeners);
    }

    Popup.prototype.createListeners = function() {
      var _this = this;
      document.getElementById("clearDB").addEventListener("click", function() {
        _this.sendMessage("storageManager", {
          title: "clearDB",
          content: ""
        }, _this.clearDBCallback);
      }, false);
    };

    Popup.prototype.sendMessage = function(module, message, callback) {
      chrome.extension.sendMessage({
        module: module,
        message: message
      }, function(response) {
        if (callback != null) {
          callback(response);
        }
      });
    };

    Popup.prototype.clearDBCallback = function(response) {
      this.displayMessage(response.message);
    };

    Popup.prototype.displayMessage = function(message) {
      var node, textnode;
      node = document.createElement("div");
      node.setAttribute("class", "notification");
      node.setAttribute("id", message.level);
      textnode = document.createTextNode(message.content);
      node.appendChild(textnode);
      document.getElementById("notifications").appendChild(node);
      setTimeout(function() {
        node.setAttribute("class", "notification hide");
        setTimeout(function() {
          document.getElementById("notifications").removeChild(node);
        }, 500);
      }, 3000);
    };

    return Popup;

  })();

  popup = new mem0r1es.Popup;

}).call(this);
